n1=int(input('Digite um numero: '))
n2=int(input("Digite outro numero: "))
s= (n1+n2)
#print("A soma dos resultados entre ",n1,"+",n2,"e igual a: ",s)
print("A soma entre {} + {} vale {}".format(n1,n2,s))
